### ISSUE TITLE
x/pkgsite: godoc.org redirect feedback - tracking issue 

### ISSUE THREAD

**Issue by julieqiu** [golang/go#39144]
This is an umbrella issue to keep track of issues related to [redirecting traffic](https://blog.golang.org/pkg.go.dev-2020) from godoc.org to pkg.go.dev. 

Issues related to this topic:

- [x] #36747: open source pkg.go.dev
- [ ] #36811: support viewing a `package@master`
- [ ] #36865: examples missing playground links
- [x] #36929: add support for bookmarklet to navigate from repository to doc
- [x] #36982: serve status badge similar to godoc.org 
- [ ] #37002: automatically fetch a requested package if it does not exist on pkg.go.dev
- [x] #37099: support package owner-initiated redirect from godoc.org to pkg.go.dev
- [x] #37863: missing source files listing
- [x] #38056: automatically link RFCs in package documentation 
- [ ] #38763: incorrect rendering of fixed-size unicode box-drawing characters
- [ ] #38892: slower loads than godoc.org 
- [x] #38986: missing links to source code for git.sr.ht
- [x] #39270: documentation misparsed as an anchor
- [x] #39529: missing documentation headings/anchors

At the moment, our priority is to work towards open sourcing (#36747) and to address [design feedback](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+label%3Ago.dev+label%3AUX+
). We will plan to address the issues above before redirecting traffic from godoc.org to pkg.go.dev.

/cc  @jba @spf13 @fflewddur @Joanne881107

**Comment by tooolbox** [comment]
Sounds fantastic @julieqiu and it's really awesome how much the feedback is being taken into account on this.

A suggestion I have on the redirect is to do it a little like Go Modules: first opt-in, then opt-out, then full switchover.  Right now you have the ability to opt-in to always redirect using a cookie, so for the next stage you could redirect *unless* a specific cookie is set.

I think this would be a very gentle way of going about it, and might spark a final round of useful feedback as the whole community adapts to the change (while still being able to browse the legacy version).

If the percentage of traffic opting-in to the redirect is very high, this suggestion may be unnecessary, but I wanted to throw it out there.

**Comment by julieqiu** [comment]
That's great suggestion - thanks @tooolbox! We'll definitely consider doing something like that, once we get closer to being ready to redirect godoc.org traffic.

**Comment by julieqiu** [comment]
Closing this issue in favor of using [milestone `pkgsite/godoc.org-redirect`](https://github.com/golang/go/milestone/157).
