### ISSUE TITLE
x/pkgsite: migrate codebase to paths-based data model

### ISSUE THREAD

**Issue by julieqiu** [golang/go#39629]
As part of the [redesign](https://github.com/golang/pkgsite#roadmap) that we have planned for this year, we will be migrating our data model to use a [paths table](https://github.com/golang/pkgsite/blob/master/migrations/000003_add_paths_table.up.sql). 

Structs and functions to be deprecated will be prefixed with "Legacy".

Related: #39621

TODOs:

- populate new tables
  - [x] update worker/postgres code to insert new data into new tables (paths, documentation, readmes, and package_imports)
- add new postgres functions
  - [x] #40032: add GetModuleInfo function to replace LegacyGetModuleInfo
  - [x] update postgres.GetImports to read from `package_imports` table
  - [x] add function to replace LegacyGetDirectory
  - [x] add GetDirectory function to return data for a path
  - [x] #40150: add a function to get the version history for a path
  - [x] #40027: add GetLicenses function to return licenses for a given path
- update frontend code:
  - [x] add new servePackagePage code path, such that:
     - [x] doc tab reads from documentation table
     - [x] overview tab reads from readmes table
     - [x] subdirectories tab reads from paths table
     - [x] versions tab reads from paths table
     - [x] imports tab reads from package_imports table
     - [x] licenses tab reads from paths table
  - [x] add new serveModulePage code path, such that:
     - [x] overview tab reads from readmes table
     - [x] packages tab reads from paths table
     - [x] versions tab reads from paths table
     - [x] licenses tab reads from paths table
  - [x] add new serveDirectoryPage code path, such that:
     - [x] overview tab reads from readmes table
     - [x] subdirectories tab reads from paths table
     - [x] versions tab exists, and reads from paths table
     - [x] licenses tab reads from paths table
  - [x] update latest badge to read from paths table
  - [x] update search to read from paths table
  - [x] move SearchResult to the internal package
- split GetDirectory into multiple queries:
  - [x] add GetDirectoryMeta
  - [x] #41018: GetReadme
  - [x] #41017: GetDocumentation
  - [x] add support for field sets
- turn on experiment flags
  - [x] InsertDirectories
  - [x] UseDirectories
  - [x] UsePathInfo
  - [x] UsePackageImports
- remove experiment flags
  - [x] InsertDirectories
  - [x] UseUnits
  - [x] UsePathInfo
  - [x] UsePackageImports
- replace use of [Legacy functions](https://github.com/golang/pkgsite/blob/master/internal/datasource.go#L40) and deprecate
  - [x] LegacyGetDirectory
  - [x] LegacyGetModuleLicenses
  - [x] LegacyGetPackage
  - [x] LegacyGetPackageLicenses
  - [x] LegacyGetPackagesInModule
  - [x] LegacyGetModuleInfo
- deprecate use of packages:
  1. replace use of packages for search upsert
    - [x] read from paths instead of packages
    - [x] drop packages FK
    - [x] fix tests
  2. do not insert into package table
    - [x] remove from insertModule
  3. remove from fetchModule
    - [x] remove LegacyPackages from fetchModule
- delete legacy structs
  - [x] LegacyDirectory
  - [x] LegacyPackage
  - [x] Module.LegacyPackages
- delete old tables / columns
  - [x] table packages (replaced by paths and documentation tables)
  - [x] table imports (replaced by package_imports table)
  - [x] columns modules.readme_file_path, modules.readme_contents (replaced by readmes table)
- change PKs:
  - [ ] change modules PK to modules.id
  - [ ] drop licenses.module_path and licenses.version
  - [x] changes licenses PK to (modules.id, filepath)
