### ISSUE TITLE
all: reopen tree for Go 1.17 development

### ISSUE THREAD

**Issue by dmitshur** [golang/go#44222]
### Current Tree Status: Open for bug fixes only (see https://github.com/golang/go/issues/44222#issuecomment-782562297)

As we're getting closer to the final Go 1.16 release, we will [soon](https://golang.org/s/release#august-1--february-1-release-issued) need to open the tree for Go 1.17 development.

As usual, the tree will initially be open to changes that must land early. Tentatively:

- [x] [CL 275297](https://golang.org/cl/275297) that bumps `internal/goversion`—this **must** be the very first CL to be submitted; CC @bcmills
- [x] dev.regabi branch will be merged to master as described [here](https://groups.google.com/g/golang-dev/c/U7eW9i0cqmo/m/ffs0tyIYBAAJ)—tracking issue #44224; CC @cherrymui, @jeremyfaller
- [x] dev.typeparam branch will be merged to master assuming the [proposal](https://github.com/golang/go/issues/43931) is accepted; CC @griesemer, @jeremyfaller
- [x] windows/arm64 @rsc 
- [x] cmd/go lazy loading refactoring @bcmills 
- [x] //go:build changes @rsc 
- [ ] _(Add/reorder any other CLs or stacks or branches that must land early.)_
- [ ] Finally, open the tree for all general Go 1.17 changes.

We will send status updates to golang-dev@ as part of this work.

This is the tracking issue for completing this task.

CC @golang/release, @ianlancetaylor.

**Comment by dmitshur** [comment]
It's planned by @golang/release for this issue to begin progressing after the Go 1.16 release is issued.

**Comment by dmitshur** [comment]
The "Current Tree Status" was just changed from "Frozen for Go 1.16 changes only" to "Accepting early Go 1.17 changes only (see list below)". I've sent a [message](https://groups.google.com/g/golang-dev/c/ZaOVCEvIUHA/m/hUFf-MveAgAJ) to golang-dev.

I'll work with @bcmills on the first CL on the list.

**Comment by bcmills** [comment]
`internal/goversion` is in. Time to merge some branches (@cherrymui, @jeremyfaller)?

**Comment by dmitshur** [comment]
Merging dev.regabi into master (issue #44224) was resolved (thank you @cherrymui). The next item currently in the list is:

- dev.typeparam branch will be merged to master assuming the [proposal](https://github.com/golang/go/issues/43931) is accepted; CC @griesemer, @jeremyfaller

When it's done (or if plans change), please update this issue and coordinate with the people working on the next item. Thank you!

**Comment by griesemer** [comment]
Quick update. Merging the dev.typeparams branch will require 1) to merge master into dev.typeparams (today), 2) isolating API changes that we may need for 1.18 but not for 1.17 (next couple of days), and then 3) merging dev.typeparams into master (hopefully by end of this week).

**Comment by rsc** [comment]
While we wait for dev.typeparams, it is OK for the cmd/go changes to proceed - I just checked and there are no changes in cmd/go on dev.typeparams.

**Comment by rsc** [comment]
It also looks OK for the windows/arm64 changes to proceed - there is no overlap except for one if statement in cmd/compile deciding about whether arm64 frame pointers are enabled, and dev.typeparams won't be changing that.

**Comment by bcmills** [comment]
The `cmd/go` changes that were ready to merge are in — we're all clear there from the perspective of opening the tree.

**Comment by griesemer** [comment]
Status update on dev.typeparams:
- we've done a recent (this afternoon) merge from master, so dev.typeparams is tracking master closely
- all outstanding CLs are in
- the build looks green but for (now) linux-ppc64le-power9osu (API check killed)

Currently we are trying to get x/tools tests to pass: They rely on go/parser and go/types which have changed significantly. We have fixed several failures and should be down to one or two at the most by tonight. Once x/tools passes, we can merge once more with master (should be clean) and then dev.typeparams can be merged into master. Maybe tomorrow, and hopefully before Monday.

**Comment by griesemer** [comment]
Status update on dev.typeparams:

- build looks green but for linux-ppc64le-power9osu (API check killed) and netbsd-argm64-bsiegert (intermittent failure)
- x/tools seems to be ok but for x/tools/internal/lsp/source (but I may not have the correct setup, @findleyr will know more)

Once the lsp tests are deemed ok we should be ready to go. Next steps:

- merge master -> dev.typeparams (expected to be trivial and conflict free)
- merge dev.typeparams -> master

**Comment by rsc** [comment]
I merged the windows/arm64 changes last night and broke a few builders. I have CLs out for those.
We should probably wait to get those fixed before doing the dev.typeparams merge, but they should be fixed soon.

**Comment by thanm** [comment]
@dmitshur FYI, Russ has asked me to do an early submit https://go-review.googlesource.com/c/go/+/293309 with the fix for https://golang.org/issue/44344. Hope that is ok.

**Comment by ianlancetaylor** [comment]
I think the guidelines should be that pure bug fixes are OK at any time.

**Comment by dmitshur** [comment]
@thanm Yes, as Russ said that CL is a follow up to the dev.regabi merge and is okay. Thanks.

**Comment by findleyr** [comment]
Status update on dev.typeparams: 

x/tools should now be green. I tested the merge in https://golang.org/cl/293770, and all Trybots succeeded ([including x/tools](https://storage.googleapis.com/go-build-log/fb7f104a/linux-amd64_df93fc3d.log)).  To be extra careful I'll also run x/tools tests on various other builders using gomote, though I'm not actually aware of changes in dev.typeparams that would cause failures on specific builders.

**Comment by rsc** [comment]
@findlyr and @griesemer are going to work on the dev.typeparams -> master merge in about an hour.
Consider the tree locked until they are done.

(The tooling requires that no commits appear on master between the preparatory master -> dev.typeparams merge and the final dev.typeparams -> master merge, so we can help them avoid doing multiple of the first merge by not submitting anything.)

Thanks!

**Comment by griesemer** [comment]
dev.typeparams has been merged into master.
(Perhaps give it 30min or so to settle on the build dashboard for a clear picture.)

**Comment by rsc** [comment]
dev.typeparams is merged.
I still have some pieces to pick up from windows/arm64, and I need to send in the //go:build CLs.
So we're not open for business yet.
But hopefully soon. 
Watch this space.

**Comment by rsc** [comment]
If any +2'ers want to help move things along, once these reformatting CLs are in I think we can soft-open the tree.
https://go-review.googlesource.com/q/o:rsc+status:open+fmt

**Comment by rsc** [comment]
I've submitted what must be submitted before soft-reopening. I'm waiting for the dashboards to clear and will post when it is time. One more reformatting CL for anyone who wants it: https://go-review.googlesource.com/c/sys/+/294490.

**Comment by rsc** [comment]
OK, things look stable enough on the dashboard. Thanks for the reviews.

**The tree is now open for bug fixes only**.

This is a soft reopening for the weekend, before the full re-opening Monday.
An email to golang-dev@ will announce the full re-opening.
Again, bug fixes only for now.
No new features, new implementations, new API, etc. (Not yet.)

The compiler underwent major surgery during the freeze in preparation for generics,
and the runtime had minor surgery in preparation for the windows/arm64 port.
There is still a bug to find to revive windows/arm (32-bit), which I'll try to do in the next few days.
Everything else seems to be working decently on the dashboard.
But certainly there are bugs, and help finding and fixing them is always appreciated. :-)

Happy hacking!

**Comment by dmitshur** [comment]
The "Current Tree Status" was updated from "Open for bug fixes only" to "Open for Go 1.17 development". I've sent an announcement to [golang-dev](https://groups.google.com/g/golang-dev/c/VNJFUxHWLHo/m/PBmGdYqoAAAJ).

Closing, as this issue is resolved. Thanks everyone!

**Comment by Budda0ne** [comment]
Q
