### ISSUE TITLE
x/tools/go/ssa: tracking issue for ssa support of slice to array casts

### ISSUE THREAD

**Issue by timothy-king** [golang/go#47326]
A new SliceToArrayPointer instruction is being [added](https://go-review.googlesource.com/c/tools/+/333749/
) to x/tools/go/ssa to support the new Go 1.17 slice to pointer-to-an-array cast. Support for this new instruction should be propagated to the golang.org packages that could be impacted by this change. Most are in golang.org/x/tools.

This issue tracks the status of golang.org packages that use ssa that may be impacted by this change. 

- [x] golang.org/x/tools/go/analysis/passes/nilness - precision can be improved.
- [x] golang.org/x/tools/go/callgraph/vta
- [x] golang.org/x/tools/go/pointer
- [x] golang.org/x/tools/cmd/guru
- [x] golang.org/x/tools/cmd/callgraph (indirect through x/tools/go/pointer)
- [x] golang.org/x/tools/godoc/analysis (indirect through x/tools/go/pointer)
- [x] golang.org/x/text/message/pipeline (indirect through x/tools/go/pointer)
- [x] golang.org/x/tools/go/ssa/interp

Other direct users of ssa that are not expected to be directly impacted:
- [x] golang.org/x/tools/go/callgraph
- [x] golang.org/x/exp/vulndb/internal/audit
- [x] golang.org/x/tools/cmd/ssadump
- [x] golang.org/x/tools/go/analysis/passes/buildssa
- [x] golang.org/x/tools/go/callgraph/cha
- [x] golang.org/x/tools/go/callgraph/rta
- [x] golang.org/x/tools/go/callgraph/static
- [x] golang.org/x/tools/go/ssa/ssautil

**Comment by timothy-king** [comment]
golang.org/x/tools/go/analysis/passes/nilness - The precision can be improved by propagating that the post condition of [reaching the next instruction after] a SliceToArrayPointer is non-nil if the array type has length >= 1 and if it is 0, the nilness of the instruction follows the nilness of the operand.

Caveat: The bit in [] is that otherwise the SliceToArrayPointer instruction panic'd. I don't think this instruction can be referred to if a panic happened so I think this is an always okay interpretation. (Needs some thought. I doubt this is a serious concern for the checker though.)

**Comment by timothy-king** [comment]
For the (indirect through x/tools/go/pointer) packages, no direct modifications are expected to be needed. x/tools/go/pointer just needs to be addressed before these packages are compatible with Go code containing slice to pointer-to-array casts.

**Comment by cuonglm** [comment]
@timothy-king For example:

```
func f() {
	var s []int
	t := (*[0]int)(s)
	println(*t)       // want "nil dereference in load"
	_ = *(*[0]int)(s) // want "nil dereference in load"

	// this operation is panic
	_ = *(*[1]int)(s) // want "nil dereference in load"
}
```

What should we do with the third conversion which can panic?

**Comment by timothy-king** [comment]
> What should we do with the third conversion which can panic?

If we know that the input to the cast is nil and the type has length >= 1, we can warn that the cast will always panic due to the nil. If it is not too much work a clearer message than "nil dereference in load" might be nice. Maybe "nil slice being cast to an array of len > 0 will always panic"?

**Comment by scott-cotton** [comment]
Here are some data points on guru

given
```
package main

import "fmt"

func main() {
	i := 0
	var sl = make([]*int, 12)
	sl[2] = &i
	var a = (*[10]*int)(sl)
	_ = a[2]
	fmt.Println(a[2])
}
```

inside of a directory named "guru"

while running guru from x/tools @6e9046bfcd341

with go version devel go1.18-a6ff433d6a Thu Aug 26 02:06:43 2021 +0000 darwin/amd64

I get
```
scott@pavillion 47326 % guru  -scope guru/guru pointsto  guru/guru.go:#119,#123
/Users/scott/Dev/47326/guru/guru.go:10.6-10.9: this *int may not point to anything.
scott@pavillion 47326 % guru  -scope guru/guru pointsto  guru/guru.go:#78,#83
/Users/scott/Dev/47326/guru/guru.go:8.2-8.6: this *int may point to these objects:
/Users/scott/Dev/47326/guru/guru.go:6:2: 	I
```

So it does not quite work right (#119,#123 refers to 'a[2]', #78,#83 refers to 'sl[2]')

Looking at the guru code, it does not seem to need to treat *ssa.SliceToArrayPointer explicitly, it seems the problem is elsewhere.
