### ISSUE TITLE
all: reopen tree for Go 1.18 development

### ISSUE THREAD

**Issue by dmitshur** [golang/go#47351]
### Current Tree Status: Tree open for all general Go 1.18 changes (see list below)

This is a tracking issue for the [upcoming task](https://golang.org/s/release#timeline) of reopening the tree for Go 1.18 development. (It's created a little early to create room for planning early CLs/branches to land during tree reopening.)

As usual, the tree will initially be open to changes that must land early:

- [x] Bump `internal/goversion.Version` to 18—this should be the very first CL to be submitted as it marks the start of `master` branch representing Go 1.18 (rather than Go 1.17). ([Example CL](https://golang.org/cl/275297).)
- [x] `dev.typeparams` branch will be merged to master (CC @mdempsky)
- [x] Finally, open the tree for all general Go 1.18 changes.

(At this time, I'm only aware of the dev.typeparams branch needing to be merged early, but the list above can be updated as needed.)

CC @golang/release.

**Comment by cuonglm** [comment]
I believe the 2nd point will overlap 1st point. On dev.typeparams, internal/goversion.Version was already 1.18 (https://github.com/golang/go/commit/ea438bda85ed473ecee215b098eba1f19113bc24#diff-b08eb4d497d366211f663b667a006b4630b51724045133b7c48913a397daf936) cc @mdempsky

**Comment by mdempsky** [comment]
@cuonglm Ack, I think it's fine though: we bump to 1.18 on master; merge master to dev.typeparams one last time and reconcile the conflict; then merge dev.typeparams back to master.

**Comment by AlekSi** [comment]
Will `dev.cmdgo` and `dev.fuzz` branches be merged into master?

**Comment by cagedmantis** [comment]
This issue will be closed now that the tree is open for general submissions.
