### ISSUE TITLE
x/build: evaluate which builders to upgrade now that Debian bullseye has been released

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#47721]
Debian 11.0 (bullseye) has been released and designated the current stable release. We should evaluate which builders should be upgraded from previous releases of Debian to newer ones. This should act as an umbrella issue for the decided upon work:

- [x]  linux-amd64-bullseye - add #47720
- [x]  linux-386 - upgrade to bullseye.
- [x]  linux-386-jessie - update the notes
- [ ]  linux-amd64 - update to bullseye
- [ ]  linux-amd64-nocgo - update to bullseye
- [ ]  linux-amd64-noopt - update to bullseye
- [ ]  linux-amd64-ssacheck - update to bullseye
- [ ]  linux-amd64-racecompile - update to bullseye
- [ ]  linux-amd64-race - update to bullseye
- [ ]  linux-amd64-jessie - update the notes
- [ ]  misc-compile - upgrade to bullseye
- [x]  linux-386-buster - add

@golang/release
