### ISSUE TITLE
tools: track tools/tooling updates to support generics

### ISSUE THREAD

**Issue by findleyr** [golang/go#50558]
Many tools and libraries that operate on Go code need to be updated to support generics. In most cases, this requires handling of the new constructs introduced in [`go/ast`](#47781) and [`go/types`](#47916).

This is a tracking issue for the status of this support. It is based on #24661, which did the same for modules, though I added several tools/packages, and removed any that have been archived or that don't work directly with Go code.

It is not the case that every tool listed here needs updates to support generics -- many will require no changes. However, any tool that interacts with Go code _might_ need to be updated, and probably needs additional tests.

Issue #50447 tracks adding a transitional API + user guide that should make it easier to get started updating third-party tools.

### How to Help

- Suggest additions to the list below. This list is certainly incomplete. Any tool or library that operates on Go code is a candidate for updating.
- Comment if you're aware of the status of generics support in any of the items below, and I'll update accordingly (or update this comment yourself if you can).
- Try building any of the tools below with Go 1.18, and test them on generic Go code. Comment with your findings.
- Send a PR to update any of the tools below to support generics (this will probably be easier once #50447 is resolved).

### List of tools / packages

- [ ] [apicompat](https://github.com/bradleyfalzon/apicompat)
- [ ] [counterfeiter](https://github.com/maxbrunsfeld/counterfeiter)
- [x] [delve](https://github.com/go-delve/delve)
- [ ] [dupl](https://github.com/mibk/dupl)
- [ ] [errcheck](https://github.com/kisielk/errcheck)
- [ ] [fillstruct](https://github.com/davidrjenni/reftools/tree/master/cmd/fillstruct) - available through `gopls`
- [ ] [goa/goagen](github.com/goadesign/goa/goagen)
- ~[go-langserver](https://github.com/sourcegraph/go-langserver)~ - use [`gopls`](golang.org/s/gopls) instead
- [ ] [go-critic](https://github.com/go-critic/go-critic)
- [ ] [go-fuzz](https://github.com/dvyukov/go-fuzz) (Note that Go 1.18 has native fuzzing)
- [ ] [go-outline](https://github.com/ramya-rao-a/go-outline) - see golang/vscode-go#1020 for implementing this functionality in gopls
- [ ] go-symbols - TODO: which fork is canonical?
- [ ] [goast-viewer](https://github.com/yuroyoro/goast-viewer)
- ~gocode~ - replaced by `gopls`
- [ ] [goconst](https://github.com/jgautheron/goconst)
- [ ] [gocyclo](https://github.com/fzipp/gocyclo) - [in progress?](https://github.com/fzipp/gocyclo/commit/44804ba326282759f6b21875e1e89840fb3aea25)
- [ ] [godef](https://github.com/rogpeppe/godef)
- [ ] [godoctor](https://github.com/godoctor/godoctor) - available through `gopls`
- [x] go doc
- [x] go fmt - also available through `gopls`
- [x] go vet - #48704; also available through `gopls`
- [ ] [gofumpt](https://github.com/mvdan/gofumpt) - also available through `gopls`
- [ ] [gogrep](https://github.com/kiransuren/gogrep) - working (https://github.com/mvdan/gogrep/issues/39)
- [ ] [golines](https://github.com/segmentio/golines)
- [ ] [gogetdoc](https://github.com/zmb3/gogetdoc)
- [ ] [golangci-lint](https://github.com/golangci/golangci-lint) - **Does not support generics yet**
- [ ] [gomodifytags](https://github.com/fatih/gomodifytags) - (see also golang/vscode-go#2002 for merging this functionality with gopls)
- [ ] [gopherjs](https://github.com/gopherjs/gopherjs)
- [ ] [goreturns](https://github.com/sqs/goreturns) - available through `gopls`
- [ ] [go-sumtype](https://github.com/BurntSushi/go-sumtype)
- [ ] [goswagger](https://github.com/go-swagger/go-swagger)
- [ ] [gotags](https://github.com/jstemmer/gotags)
- [ ] [gotests](https://github.com/cweill/gotests)
- [ ] [gotext](https://godoc.org/golang.org/x/text/cmd/gotext)
- [ ] [gqlgen](https://github.com/99designs/gqlgen)
- [ ] [impl](https://github.com/josharian/impl) - see also #37537 for merging this functionality with gopls
- [ ] [ineffassign](https://github.com/gordonklaus/ineffassign)
- [ ] [keyify](https://github.com/dominikh/go-tools/tree/master/cmd/keyify)
- [ ] [lll](https://github.com/walle/lll) - likely no update required
- [ ] [maligned](https://github.com/mdempsky/maligned)
- [ ] [misspell](https://github.com/client9/misspell)
- [ ] [moq](https://github.com/matryer/moq)
- [ ] [mockery](https://github.com/vektra/mockery)
- [ ] [motion](https://github.com/fatih/motion)
- [ ] [nakedret](https://github.com/alexkohler/nakedret)
- [ ] [pkgsite](https://github.com/golang/pkgsite) - #48264
- [ ] [revive](https://github.com/mgechev/revive)
- [ ] [semgrep](https://github.com/dgryski/semgrep-go)
- [ ] [staticcheck](https://staticcheck.io/) - also available through `gopls`. **Does not support generics yet**
- [ ] [unconvert](https://github.com/mdempsky/unconvert)
- [ ] [unparam](https://github.com/mvdan/unparam)
- [ ] x/tools/cmd/bundle
- ~x/tools/cmd/godoc~ - [replaced by pkgsite](https://github.com/golang/go/issues/49212)
- [x] x/tools/cmd/goimports - also available through `gopls`
- [x] x/tools/cmd/gotype - no update required
- [ ] x/tools/cmd/gomvpkg
- [ ] x/tools/cmd/gorename - available through `gopls`
- ~x/tools/cmd/guru~ - replaced by `gopls`
- [x] x/tools/cmd/stringer - https://golang.org/cl/355313
- [x] x/tools/go/analysis - no update required (TODO: add individual analyzers where relevant)
- [x] x/tools/go/analysistest - no update required
- [x] x/tools/go/ast/astutil
- [x] x/tools/go/ast/inspector
- ~x/tools/go/loader~ - Deprecated: replaced by go/packages
- [x] x/tools/go/packages
- [ ] x/tools/go/ssa - #48525
- [x] x/tools/go/types/objectpath
- [x] x/tools/go/types/typeutil
- [ ] x/tools/gopls - works with _default_ options; some analyzers may panic
- [ ] x/tools/refactor/eg
- [ ] x/tools/refactor/rename
- [ ] x/tools/refactor/satisfy

**Comment by mvdan** [comment]
I think the gogrep entry is a bit confusing :) The link doesn't point to a Go analysis tool, and the linked issue is about support for modules. Also, note that the actual repo has been archived, so I think we can just omit it entirely, unless there's a healthy fork somewhere.

For gofumpt, I think it already supports type parameters (https://github.com/mvdan/gofumpt/blob/ba9bdf90c2757f830763edbfb9ab401a50012fa8/testdata/scripts/typeparams.txt), so we can probably mark it as done unless there's a specific bug or missing feature you can point me to.

**Comment by findleyr** [comment]
> I think the gogrep entry is a bit confusing :) 

Whoops! I started with the list from #24661, and missed that link.  I removed the gogrep item, and marked gofumpt as done. Thanks!

**Comment by mvdan** [comment]
In terms of the other tools, you already mentioend https://github.com/golang/go/issues/50447, and I think https://github.com/golang/go/issues/48525 also deserves a mention as a blocker. Some static analysis tools, like unparam or staticcheck, depend on SSA.

**Comment by thepudds** [comment]
Hi @findleyr One thing that might be helpful is a pointer to a body of generic Go code to test against?

For example, I've pitched in a bit on dvyukov/go-fuzz, and I've confirmed that a hello world generic target seems to work, but I suspect more complicated examples might have problems. A while ago, I pulled together a small set of generics examples, but probably not representative enough, and it might be helpful to have a pointer here to a good set of examples.

Also, in case you haven't already seen this, there is a list of ~80 utilities here https://github.com/golangci/golangci-lint/pull/2438#issue-1090001715 with some high-level status for generics support, including red X's for "known to panic on generic code.

**Comment by nevkontakte** [comment]
https://github.com/gopherjs/gopherjs/issues/1013 is the specific issue that tracks Generics support in GopherJS.

**Comment by zephyrtronium** [comment]
@thepudds 

> Hi @findleyr One thing that might be helpful is a pointer to a body of generic Go code to test against?

The test cases in [test/typeparam](https://github.com/golang/go/tree/master/test/typeparam) might be useful for that.

**Comment by findleyr** [comment]
@thepudds thank you! Sorry for the slow turnaround: I will incorporate that list along with what I know about `x/tools` analyzers.

Regarding a corpus of generic code: @zephyrtronium's suggestion of `test/typeparam` is good. I also sometimes use [`go/types/testdata/examples`](https://cs.opensource.google/go/go/+/master:src/go/types/testdata/examples/). But the point stands: I think we should perhaps consider including a small corpus in the soon-to-be-created `x/exp/typeparams` module.

**Comment by ipfans** [comment]
Due to golangci-lint [v1.45.0](https://github.com/golangci/golangci-lint/releases/tag/v1.45.0) being released, I think its status is now supported.

**Comment by findleyr** [comment]
Thanks @ipfans -- I updated to note that golangci-lint has partial generics support.

**Comment by wxolp** [comment]
https://github.com/go-critic/go-critic/issues/1193

**Comment by mvdan** [comment]
> Regarding a corpus of generic code: @zephyrtronium's suggestion of `test/typeparam` is good. I also sometimes use [`go/types/testdata/examples`](https://cs.opensource.google/go/go/+/master:src/go/types/testdata/examples/). But the point stands: I think we should perhaps consider including a small corpus in the soon-to-be-created `x/exp/typeparams` module.

I was wondering what's the current status of this, if it has evolved :) I tried using go/types/testdata/examples, but it contains some `/* ERROR ... */` lines, presumably failing to typecheck on purpose - so it's no good as-is as a generic code corpus for tools. I also found https://github.com/golang/exp/tree/master/typeparams/example, though it seems to be a collection of example tools, so it's not quite what I'm after either.

**Comment by mvdan** [comment]
To give some more context: I'm after hundreds of lines of Go code, not thousands or tens of thousands, because that code will need to be copied to each of the modules for the tools which I need to ensure don't panic on e.g. unexpected `go/ast` nodes for generic code. I imagine that one wouldn't need _that_ much code to represent most syntax and typechecking edge cases :)

**Comment by findleyr** [comment]
@mvdan 

> I was wondering what's the current status of this, if it has evolved :)

No status change as far as I know, sorry. I think we'd welcome an addition to x/exp/typeparams. Perhaps the corpus should be available as an importable package within that module? Would that work for your purposes, or would you more likely make a copy?

> I tried using go/types/testdata/examples, but it contains some /* ERROR ... */ lines, presumably failing to typecheck on purpose

Yes, those comments denote expected errors. 

>  - so it's no good as-is as a generic code corpus for tools.

That depends on whether you want to test your tool in the presence of errors, I suppose, but your point stands. I think a good starting point for a corpus may be to filter out those error cases.

**Comment by zchee** [comment]
@findleyr very nits, but goa/goagen link url is now `https://github.com/golang/go/issues/github.com/goadesign/goa/goagen`.

**Comment by findleyr** [comment]
> @findleyr very nits, but goa/goagen link url is now `https://github.com/golang/go/issues/github.com/goadesign/goa/goagen`.

Thanks. That URL doesn't look right (it starts with github.com/golang...), but I updated the goagen URL based on a Google search. Please let me know if it's still not right.

**Comment by zchee** [comment]
@findleyr Thanks for fix.

But, I'm not familiar with goa, but goa seems to already released `v3` using `v3` _default_ branch. Also `gen` move to subcommand.
- https://github.com/goadesign/goa#2-implement

So, I think correct URL is just:
`https://github.com/goadesign/goa`.
