### ISSUE TITLE
update release-branch.go1.18 with changes for Go 1.18 final (Go 1.18.1 and future minor releases are out of scope)

### ISSUE THREAD

**Issue by dmitshur** [golang/go#51460]
The [release-branch.go1.18](https://go.googlesource.com/go/+log/refs/heads/release-branch.go1.18) branch as of this moment points to commit golang/go@cb5a598d7f2ebd276686403d141a97c026d33458, from when the Go 1.18 RC 1 release was made. Before the final Go 1.18 release, the branch needs to be updated to include all changes that are meant for Go 1.18, both those that landed while the tree was frozen, and a number of additional fixes that landed after the tree reopened for 1.19.

This is the tracking umbrella issue to collect the remaining CLs that need to land on the release branch, and sort them all. **CLs that need to submitted first are on top of the list**:

- [x] https://go.dev/cl/389554: [release-branch.go1.18] all: merge master (acc5f55) into release-branch.go1.18
          ⤷ #51209
          ⤷ #51324
          ⤷ everything else up to "internal/goversion: update Version to 1.19"
- [x] https://go.dev/cl/388918: [release-branch.go1.18] cmd/compile: use AutogeneratedPos for method value wrapper
- [x] https://go.dev/cl/387977: go/types, types2: correctly consider ~ (tilde) in constraint type inference
- [x] https://go.dev/cl/388294: go/types, types2: clarify a comment and add an extra test
- [x] https://go.dev/cl/389474: cmd/compile: don't include instantiating types in type hash
          ⤷ #51250
- [x] https://go.dev/cl/389575: [release-branch.go1.18] cmd/go: ignore the workspace when running a package at a specified version
          ⤷ #51390
- [x] https://go.dev/cl/389594: go/types, types2: fix scoping for iteration variables declared by range clause
          ⤷ #51437
- [x] https://go.dev/cl/388995: [release-branch.go1.18] runtime: count spill slot for frame size at finalizer call
          ⤷ #51457
- [x] https://go.dev/cl/389298: [release-branch.go1.18] cmd/go: make paths consistent between 'go work init' and 'go work use'
          ⤷ #51448
- [x] https://go.dev/cl/389299: [release-branch.go1.18] cmd/go: error out of 'go work use' if no directories are given
          ⤷ #51448
- [x] https://go.dev/cl/389914: [release-branch.go1.18] cmd/go: add links to workspaces reference and tutorial to go help work
          ⤷ #51301
- [x] https://go.dev/cl/390022: [release-branch.go1.18] syscall: remove TestRlimit
          ⤷ #51479
- [x] https://go.dev/cl/390095: [release-branch.go1.18] internal/fuzz: handle Inf/NaN float values
          ⤷ #51258
- [x] https://go.dev/cl/390214: internal/fuzz: fix TestUnmarshalMarshal on MIPS
          ⤷ #51258
- [x] https://go.dev/cl/390025: go/types, types2: correctly include comparable in type set intersection
          ⤷ #51472
- [x] https://go.dev/cl/390314: go/types, types2: don't crash in selectors referring to the type being declared
          ⤷ #51509
- [x] https://go.dev/cl/390041: go/types, types2: record all type instances, even duplicates
          ⤷ #51494
- [x] https://go.dev/cl/390039: go/types: document that predicates are undefined on generic types
          ⤷ #50887
- [x] https://go.dev/cl/387934: go/types, types2: disable inference for type instances
          ⤷ #51527
- [x] https://go.dev/cl/390578: cmd/compile/internal/types2: more consistently print "check
 go.mod" if language version < 1.18
          ⤷ #51531
- [x] https://go.dev/cl/390816: [release-branch.go1.18] internal/fuzz: fix encoding for out-of-range ints and runes
          ⤷ #51528
- [x] https://go.dev/cl/390914: go/printer: don't print unnecesary commas for func type param lists
         ⤷ #51548
- [x] https://go.dev/cl/388194: cmd/go: fix buildvcs when using older git versions
         ⤷ #51253
- [x] https://go.dev/cl/391135: go/types, types2: disable field accesses through type parameters
         ⤷ #51576
- [x] https://go.dev/cl/391154: go/types, types2: clarify documentation with respect to generic types
         ⤷ #49593
- [x] https://go.dev/cl/391275: go/types, types2: pointer base types cannot be type constraints
         ⤷ #51578
- [x] https://go.dev/cl/391475: cmd/compile: fix transform of OEQ/ONE when one arg is a type param
         ⤷ #51522
- [x] https://go.dev/cl/391594: cmd/compile: fix expression switches using type parameters
         ⤷ #51522
- [x] https://go.dev/cl/391615: go/types, types2: remove incorrect assertion (don't crash)
         ⤷ #51593
- [x] https://go.dev/cl/391614: internal/fuzz: don't use dirty coverage maps during minimization
         ⤷ #48326
- [x] https://go.dev/cl/391454: internal/fuzz: minimization should not reduce coverage
         ⤷ #48326
- [x] https://go.dev/cl/391574: cmd/compile: fix re-export closure
         ⤷ #51423
- ~https://go.dev/cl/392614: [release-branch.go1.18] cmd/compile: fix wrong dict param when getting dict type~
          ⤷ #51413 (to be considered for Go 1.18.1)
- [x] https://go.dev/cl/392674: [release-branch.go1.18] doc: update go_spec.html with latest changes
          ⤷ #51532
- final Go 1.18 release

(The boxes can be checked after the corresponding CLs are submitted to release-branch.go1.18.)

CC @golang/release, @randall77, @griesemer.

**Comment by randall77** [comment]
CL 389474 to fix #51250

**Comment by dmitshur** [comment]
Thanks, added it to the list.

**Comment by dmitshur** [comment]
By now, [CL 389554](https://go.dev/cl/389554) landed, so release-branch.go1.18 has all "for 1.18" CLs that landed while the tree was still frozen for 1.18 development. Next up are the fixes since then.

I reviewed all [open release-blocking issues](https://github.com/golang/go/issues?q=is%3Aopen+is%3Aissue+milestone%3AGo1.18+label%3Arelease-blocker) in Go 1.18 milestone, as well as [open CLs](https://go-review.googlesource.com/q/repo:go+branch:release-branch.go1.18+status:open) targeting the Go 1.18 release branch and made sure everything in those 2 lists is included above. Then confirmed their order. Based on that, preparing the following stack that will check off all the boxes present at the time of this comment:

```
$ git switch release-branch.go1.18 && git pull --ff-only
$ git codereview change release-118-work

$ git show --oneline --no-decorate HEAD
9f2f0ee6ce [release-branch.go1.18] all: merge master (acc5f55) into release-branch.go1.18

git cherry-pick b0db2f00a0d540c3d3f5d14433da2e3e1ad41f9f  # cmd/compile: use AutogeneratedPos for method value wrapper
git cherry-pick 0807986fe6bf6040bafa9c415ab72e4cc8e519a4  # go/types, types2: correctly consider ~ (tilde) in constraint type inference
git cherry-pick 6da16b6ad5787a043fc9978d2d009934e3b2e165  # go/types, types2: clarify a comment and add an extra test
git cherry-pick d3672054fb58d5eaa241f15fa9d7fb9d61e9ac05  # cmd/compile: don't include instantiating types in type hash
git cherry-pick 86b5f6a7be707b9d84108df6f459c7e84bf9dbac  # cmd/go: ignore the workspace when running a package at a specified version
git cherry-pick d3fe4e193e387f250ba53a80f669eac465b1641d  # go/types, types2: fix scoping for iteration variables declared by range clause
git cherry-pick 58804ea67a28c1d8e37ed548b685bc0c09638886  # runtime: count spill slot for frame size at finalizer call
git cherry-pick 87a345ca3849a68de13f29bdc7628f2943734946  # cmd/go: make paths consistent between 'go work init' and 'go work use'
git cherry-pick 4f8094386c3c015f6b6f3efc3a002d188433d388  # cmd/go: error out of 'go work use' if no directories are given
git cherry-pick 1eb1f621da20d7c93ac0312e59c08afbde4d9f56  # cmd/go: add links to workspaces reference and tutorial to go help work
```

Mailed out the stack (10 commits) with https://go.dev/cl/389914 at the top.

**Comment by ianlancetaylor** [comment]
CL 390020 should be backported to the 1.18 branch for #51479.  I can do the backport if you like.

**Comment by dmitshur** [comment]
Thanks Ian. It is probably better if I add it to the top of the existing stack for better visibility, and it's very easy for me to do since there aren't any conflicts. It's sent as [CL 390022](https://go.dev/cl/390022).

**Comment by rolandshoemaker** [comment]
[CL 388354 ](https://go-review.googlesource.com/c/go/+/388354) has just landed and should be backported, thanks!

**Comment by dmitshur** [comment]
Thanks! Added and mailed https://go.dev/cl/390095.

**Comment by griesemer** [comment]
[CL 390025](https://go-review.googlesource.com/c/go/+/390025) needs to be backported once it has landed.

**Comment by griesemer** [comment]
[CL 390314](https://go-review.googlesource.com/c/go/+/390314) needs to be backported once it has landed.

**Comment by rolandshoemaker** [comment]
[CL 390214](https://go-review.googlesource.com/c/go/+/390214) has landed and should be backported, thanks!

**Comment by bcmills** [comment]
I just merged [CL 390424](https://go.dev/cl/390424), and it should have a backport too.

**Comment by findleyr** [comment]
https://go.dev/cl/390914 should be cherry-picked too.

**Comment by bcmills** [comment]
https://go.dev/cl/388194, although if it doesn't make the boat it can probably wait for 1.18.1.

**Comment by griesemer** [comment]
[CL 391135](https://go.dev/cl/391135) needs to be cherry-picked once it has landed.

**Comment by findleyr** [comment]
[CL 391154](https://go-review.googlesource.com/c/go/+/391154/) should also be cherry-picked once it has landed.

**Comment by griesemer** [comment]
[CL 391275](https://go.dev/cl/391275) needs to be cherry-picked once it has landed.

**Comment by griesemer** [comment]
[CL 391615](https://go-review.googlesource.com/c/go/+/391615) needs to be cherry-picked.

Background: The fix simply removes an incorrect assertion (it was always incorrect). The rest of the changes is tests and the port to `go/types`. This CL will change the relevant issue [#51593](https://golang.org/issue/51593) from a release-blocker (crash) to a bug for Go 1.19.

**Comment by rolandshoemaker** [comment]
[CL 391454](https://go-review.googlesource.com/c/go/+/391454) and [CL 391614](https://go-review.googlesource.com/c/go/+/391614) should be backported (and with that, I think I'm done with 1.18... 🤞.)

**Comment by cuonglm** [comment]
[CL 391994](https://go-review.googlesource.com/c/go/+/391994) needs to be cherry-picked.

Background: for generic code, the compiler was using the wrong dict param for getting the dictionary type, causing mis-compile code when disable inlining. Debuggers (like devel) will have issues debugging generic code.

**Comment by dmitshur** [comment]
Thanks @cuonglm.

At this point we are very close to the release and so the bar for fixes is very high. Per [go.dev/s/release](https://go.dev/s/release#july-1--january-1-release-candidate-1-issued), "We may prefer to issue a release with a known but very rare crash than to issue a release with a new but not production-tested fix."

I will make a backport for CL 391994, make sure it passes tests, and then generate a CL for resolving #51532, at which point we will need to aim to stop changing release-branch.go1.18 for anything but the most critical issues that must block the final release. For everything else, we'll need to consider backports to minor releases, or waiting for Go 1.19. Thanks.

**Comment by cuonglm** [comment]
@dmitshur Thanks for clarifying, I made https://go-review.googlesource.com/c/go/+/392614 for backport CL 391994.

IMHO, that's a critical issue, which make compiler generate invalid code and can cause runtime crashes/wrong behavior. We were able to catch that bug with inlining disable does not mean we have enough coverage test case for making sure the bug won't happen with inlining enable.

How do you think @randall77 @mdempsky ?

**Comment by dmitshur** [comment]
@cuonglm @randall77 Thanks.

[CL 392674](https://go.dev/cl/392674) is the last CL needed resolve a release-blocking issue in 1.18 milestone, so after it's in, I will tentatively close this issue.

**Comment by dmitshur** [comment]
Ok, as of this writing we are down to just 3 release-blocking issues in the Go1.18 milestone:

- #47694
    - all that's left is to submit [CL 390375](https://go.dev/cl/390375) in x/website on the day of the release
- #11811
   - an umbrella tracking issue, doesn't need CLs in the main repository
- (this issue)

I'll mark this closed since the `release-branch.go1.18` should have all the intended CLs that are needed for Go 1.18 final. (Everything to be cherry-picked for 1.18.1 will happen later—it's outside of scope of this issue.) Thanks to everyone's help here.
