### ISSUE TITLE
x/tools/go/ssa: tracking turning ssa.InstantiateGenerics mode on

### ISSUE THREAD

**Issue by timothy-king** [golang/go#52504]
This is a tracking bug for whether to enable ssa.InstantiateGenerics as a part of the ssa.BuilderMode for ssa construction in x/tools. 

Part of the larger effort of https://github.com/golang/go/issues/48525.

Subdirectories that need to be checked:
- [x] ./cmd/callgraph
- [x] ./cmd/ssadump
- [x] ./go/analysis/passes/buildssa
- [x] ./go/analysis/passes/nilness
- [x] ./go/analysis/passes/unusedwrite
- [x] ./go/callgraph
- [x] ./go/callgraph/cha
- [x] ./go/callgraph/rta
- [x] ./go/callgraph/static
- [x] ./go/callgraph/vta
- [x] ./go/pointer
- [x] ./go/ssa
- [x] ./go/ssa/interp
- [x] ./go/ssa/ssautil

Checking should cover tests as well.

Edit: Considering `./cmd/guru` addressed for the purpose of tracking as there are no action items for it at the moment. For now progress here is blocked on the larger decision about whether guru will support generics. That needs to be decided first.
