### ISSUE TITLE
x/tools/gopls: switch to new diff implementation (umbrella)

### ISSUE THREAD

**Issue by findleyr** [golang/go#52967]
This is an umbrella issue tracking the work to switch to the new diff implementation being worked on by @pjweinb in https://go.dev/cl/396855.

Rough outline of steps:

- [x] #52966: Land the new implementation, with the "both" algorithm option comparing old and new.
- [x] Run this for a week or so among the team or any early adopters.
- [x] Enable "both" on the vscode-go nightly release, with bug reporting enabled.
- [x] Make the new diff algorithm the default, with an option to revert to the old diff algorithm.
- [x] Remove the old diff algorithm, and the dependency on go-diff.

**Comment by findleyr** [comment]
Done for v0.14.0. Will delete the old diff in v0.15.0.
