### ISSUE TITLE
all: reopen tree for Go 1.20 development

### ISSUE THREAD

**Issue by joedian** [golang/go#53812]
### Current Tree Status: Open for Go 1.20 development

This is a tracking issue for the [upcoming task](https://go.dev/s/release#timeline) of reopening the tree for Go 1.20 development. (It's created a little early to create room for planning early CLs/branches to land during tree reopening.)

As usual, the tree will initially be open to changes that must land early:

- [x] https://go.dev/cl/420816 - Bump `internal/goversion.Version` to 20—this should be the very first CL to be submitted as it marks the start of `master` branch representing Go 1.20 (rather than Go 1.19). ([Example CL](https://go.dev/cl/341590).) (@dmitshur)
- [x] Clean up `_p_` / `_g_` (@prattmic)
- [x] Go 1.17 bootstrap (@rsc)
- [x] Refactor lock ranking (@aclements, optional)
- [x] Update golang.org/x dependencies for #36905 (@dmitshur)
- [x] Unified IR merge (@mdempsky)
- [x] Soft open for bug and stability fixes only, no new features yet (Thursday, Aug 4).
- [x] Finally, open the tree for all general Go 1.20 changes (Monday, Aug 8).

CC @golang/release.

**Comment by prattmic** [comment]
We discussed a few early-in-cycle CLs last week in https://github.com/golang/go/issues/43930#issuecomment-1195933312:

* [CL stack](https://go.dev/cl/418574) cleaning up use of `_p_` and `_g_` in the runtime (@prattmic, high priority, lots of conflict potential)
* [CL stack](https://go.dev/cl/418592) refactoring runtime lock ranking (@aclements, medium priority, would conflict hard with any lock rank changes)
  * @aclements is unavailable for a few days, so this may need to wait. We can avoid conflicts by ensuring we don't merge any changes to `src/runtime/lockrank.go`.

A few others that have come up:

* [1-bit heap bitmap](https://go.dev/cl/407035) (@randall77, major change, should have lots of soak time)
* [Change GC pacer to moving average](https://go.dev/cl/417558) (@mknyszek, soak time)

These two are mostly about soak time, not conflicts, so I defer to their authors about whether they need to be in the "early in cycle" hold period.

**Comment by rsc** [comment]
I'd like to get the "Go 1.17 as bootstrap toolchain" sequence [CL 420215 and below](https://go.dev/cl/420215) landed early-in-cycle, because if there is any builder breakage it will be less disruptive when the tree is quieter. (I am of course doing extensive testing to try to avoid any breakage at all, but you never know.)

**Comment by randall77** [comment]
The 1-bit heap bitmap CL doesn't need to be early-in-cycle. I'll just get it in when the full tree opens.

**Comment by dmitshur** [comment]
The Go 1.19 release is out, so the tree will be reopening soon (for early in cycle changes first, then generally). I'll work on the first CL to bump goversion.Version.

**Comment by mdempsky** [comment]
Just to minimize the merge race window (master->dev.unified branch sync, and then dev.unified->master merge), I'd like to merge dev.unified before we open for general development. But I'm happy to do this after any other early-in-cycle CLs have landed. I don't expect this to interfere with any other early CLs.

**Comment by dmitshur** [comment]
We need to update standard-library dependencies (#36905), and it seems like a good idea to fit that in before the general tree opening. I'll take care of it.

**Comment by mdempsky** [comment]
dev.unified has been merged back into master: https://go-review.googlesource.com/c/go/+/421374

**Comment by dmitshur** [comment]
Everything that was planned is in, I've updated the tree status heading to say that bug fixes and stability improvement CLs are okay to land, and the tree can be fully opened on Monday.

**Comment by dmitshur** [comment]
We're ready to complete the tree reopening. Updated the tree status heading to "Open for Go 1.20 development". Happy development!
