### ISSUE TITLE
x/build/cmd/gomote: CLI UI improvements tracking issue

### ISSUE THREAD

**Issue by mknyszek** [golang/go#53956]
Goal: fix up the gomote UI by tackling the following GitHub issues,
* https://github.com/golang/go/issues/32430 gomote takes several commands for very common setup
* https://github.com/golang/go/issues/29037 gomote commands are too long (kind of, this issue is more about the SSH environment, but the common steps of "push, make.bash" are so common they should probably have a shortcut)
* https://github.com/golang/go/issues/53273 puttar is confusing

and directly add support for the common use-case of stress testing across several gomotes, a la
* https://github.com/mknyszek/goswarm

Proposed list of changes to the frontend:
- [x] Add stateful gomote "groups" that can be used to both shorten gomote commands and manipulate several gomotes at once
    - [x] State will be stored in os.UserConfigDir + "/gomote/groups"
    - [x] Existing commands can either apply to individual gomote instances or groups via the `-group` flag or `GOMOTE_GROUP`
    - [x] Add the -count flag to the "create" subcommand for creating multiple gomotes
    - [x] Add the -setup flag to the "create" subcommand for automatically pushing and running ./make.ba{sh|t}
    - [x] Add the -until=<regexp> flag to the "run" subcommand
    - [x] Add the -collect flag to automatically "gettar" after a "run."
    - [x] Make "gettar" no longer write to stdout by default.
    - [x] Make "puttar" have a nicer argument structure. 

The example below demonstrates the new functionality. Following examples build on each other.

```
$ GOROOT=/path/to/goroot gomote group start my-group
Started gomote group my-group
$ gomote group list
Name          Instances       GOROOT
my-group    (none)
$ gomote -group=my-group create -count=2 -setup linux-amd64
Creating linux-amd64 gomote (1)...
Creating linux-amd64 gomote (2)...
Pushing GOROOT to user-mknyszek-linux-amd64-0...
Pushing GOROOT to user-mknyszek-linux-amd64-1...
Running ./make.bash on user-mknyszek-linux-amd64-0...
Running ./make.bash on user-mknyszek-linux-amd64-1...
$ export GOMOTE_SESSION=my-group
$ gomote create -count=1 -setup windows-amd64
Creating windows-amd64 gomote (1)...
Pushing GOROOT to user-mknyszek-windows-amd64-0...
Running ./make.bat on user-mknyszek-windows-amd64-0...
$ gomote group list
Name          Instances                        GOROOT
my-group    user-mknyszek-linux-amd64-0      /path/to/goroot
              user-mknyszek-linux-amd64-1
              user-mknyszek-windows-amd64-0
$ gomote run go/bin/go test -run="FlakyTest" -count=1000 runtime
PASS
$ gomote run -until-failure='unexpected return pc' go/bin/go test -run="FlakyTest" -count=1000 runtime
runtime: unexpected return pc
...
FAIL
```

- [ ] Factor out high-level gomote instance manipulation into a library.

**Comment by mknyszek** [comment]
FWIW, I'm not 100% convinced myself that "sessions" are the right name or abstraction; they are a bit clunky. But, at the very least it makes working with just 1 gomote a bit easier than before.

I'm thinking I might rename them to groups. And maybe add a flag such that you can create a bunch of gomotes and add them to a new group directly.

**Comment by mknyszek** [comment]
I scaled down the scope a little bit as the week comes to an end. One enticing proposition out of all this is I have now factored out most of the gomote control bits from the actual command glue, so those can pretty easily turn into a high-level gomote control library for "scripting" purposes.

**Comment by mknyszek** [comment]
The main changes landed. (There could be a bit more refactoring and cleanup, but it seems OK for now.) Closing this issue.
