### ISSUE TITLE
all: reopen tree for Go 1.21 development

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#57736]
### Current Tree Status: Tree open for Go 1.21 general development

This is a tracking issue for the [upcoming task](https://golang.org/s/release#timeline) of reopening the tree for Go 1.21 development. (It's created a little early to create room for planning early CLs/branches to land during tree reopening.)

As usual, the tree will initially be open to changes that must land early:

- [x] Bump `internal/goversion.Version` to 21—this should be the very first CL to be submitted as it marks the start of `master` branch representing Go 1.21 (rather than Go 1.20). ([Example CL](https://golang.org/cl/275297).)
  - #40705
- [x] Large stack of `go/types` changes [go.dev/cl/461495](https://go.dev/cl/461495) (@griesemer)
- [x] Stack of reproducibility-related and go.env fixes [CL 462199](https://go.dev/cl/462199) and parents (@rsc)
- ~~[ ] Any CLs associated with issues labelled as `early-in-cycle`. (Detailed list being compiled) (None)~~
- [x] Submit CLs that are already approved and marked AutoSubmit, but blocked on wait-release
- [x] Finally, open the tree for all general Go 1.21 changes.

CC @golang/release.

**Comment by bcmills** [comment]
Note that since we now have `Auto-Submit` and it knows about the `No-Wait-Release` condition, we should be careful not to remove `wait-release` CL hashtags until the tree is fully open for general changes.

**Comment by cherrymui** [comment]
The tree is open now. Thanks.
