### ISSUE TITLE
doc: write release notes for Go 1.21

### ISSUE THREAD

**Issue by thanm** [golang/go#58645]
This is the tracking issue for writing the Go 1.21 Release Notes. The version at tip can be viewed at https://tip.golang.org/doc/go1.21.

When the Go 1.21 Release Notes are complete, this should be closed, and a similar issue should be made for the next release. Previous issues are https://github.com/golang/go/issues/54202, https://github.com/golang/go/issues/51400, https://github.com/golang/go/issues/47694, https://github.com/golang/go/issues/44513, etc.

**Comment by dmitshur** [comment]
Reopening (due to #29599).

**Comment by dmitshur** [comment]
Reopening a second time (due to #21312). 😮‍💨

**Comment by dmitshur** [comment]
Writing down a few of the known remaining tasks needed to close out this release-blocking issue:

- [ ] resolve a `go/types` TODO still visible at https://tip.golang.org/doc/go1.21#go/types
    - https://go.dev/cl/513475 resolves it and needs to be submitted
- [ ] review any open CLs that are updating doc/go1.21.html (https://go-review.googlesource.com/q/path:doc/go1.21.html+status:open+-label:Hold%3D%252B1)
- [ ] move doc/go1.21.html from main Go repo to x/website/_content/doc (like [CL 464075](https://go.dev/cl/464075) and [CL 464055](https://go.dev/cl/464055) did it for 1.20 release notes)
- [ ] run [relnote](https://golang.org/x/build/cmd/relnote) for the last time to find out whether any additional changes have been flagged for release notes
- [ ] on release day itself, delete the "Go 1.21 is not yet released. These are work-in-progress release notes. Go 1.21 is expected to be released in August 2023." notice (this is in scope of the go1.21.0 release process itself)
    - The CL removing that draft notice will also mark this issue closed.

**Comment by dr2chase** [comment]
Backlink to TODO list at https://github.com/golang/go/issues/58645#issuecomment-1662611308 since otherwise it gets lost in the "hidden items".
