### ISSUE TITLE
x/build: create LUCI GCE builders

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#60436]
As part of a migration to a new CI/CD system, there is a need to create images for the machines hosted on the Go GCP project. This is a list of the builders which are currently hosted on the project. This list will be used to seed which images must be built in order to support all of these builders.

## Builders
- [ ] android-386-emu (Container image)
- [ ] android-amd64-emu (Container image)
- [ ] dragonfly-amd64-622 (GCE VM Image)
- [ ] freebsd-386-12_3 (GCE VM Image)
- [ ] freebsd-386-13_0 (GCE VM Image)
- [ ] freebsd-amd64-12_3 (GCE VM Image)
- [ ] freebsd-amd64-13_0 (GCE VM Image)
- [ ] freebsd-amd64-race (GCE VM Image)
- [ ] js-wasm (Container image)
- [ ] js-wasm-node18 (Container image)
- [ ] linux-386 (Container image)
- [ ] linux-386-bullseye (Container image)
- [ ] linux-386-buster (Container image)
- [ ] linux-386-clang (Container image)
- [ ] linux-386-longtest (Container image)
- [ ] linux-386-sid (Container image)
- [ ] linux-386-softfloat (Container image)
- [ ] linux-386-stretch (Container image)
- [ ] linux-amd64 (Container image)
- [ ] linux-amd64-alpine (Container image)
- [ ] linux-amd64-androidemu (Container image)
- [ ] linux-amd64-boringcrypto (Container image)
- [ ] linux-amd64-bullseye (Container image)
- [ ] linux-amd64-buster (Container image)
- [ ] linux-amd64-clang (Container image)
- [ ] linux-amd64-fedora (Container image)
- [ ] linux-amd64-goamd64v3 (Container image)
- [ ] linux-amd64-longtest (Container image)
- [ ] linux-amd64-longtest-race (Container image)
- [ ] linux-amd64-nocgo (Container image)
- [ ] linux-amd64-noopt (Container image)
- [ ] linux-amd64-nounified (Container image)
- [ ] linux-amd64-perf (Container image)
- [ ] linux-amd64-race (Container image)
- [ ] linux-amd64-racecompile (Container image)
- [ ] linux-amd64-sid (Container image)
- [ ] linux-amd64-ssacheck (Container image)
- [ ] linux-amd64-staticlockranking (Container image)
- [ ] linux-amd64-stretch (Container image)
- [ ] linux-amd64-vmx (Container image)
- [ ] linux-arm64 (Container image)
- [ ] linux-arm64-boringcrypto (Container image)
- [ ] linux-arm64-longtest (Container image)
- [ ] linux-s390x-crosscompile (Container image)
- [ ] misc-compile-aix-ppc64 (Container image)
- [ ] misc-compile-darwin-amd64 (Container image)
- [ ] misc-compile-darwin-arm64 (Container image)
- [ ] misc-compile-dragonfly-amd64 (Container image)
- [ ] misc-compile-freebsd-386 (Container image)
- [ ] misc-compile-freebsd-arm (Container image)
- [ ] misc-compile-freebsd-arm64 (Container image)
- [ ] misc-compile-freebsd-riscv64-go1.20 (Container image)
- [ ] misc-compile-illumos-amd64 (Container image)
- [ ] misc-compile-linux-arm (Container image)
- [ ] misc-compile-linux-arm-arm5 (Container image)
- [ ] misc-compile-linux-loong64 (Container image)
- [ ] misc-compile-linux-mips (Container image)
- [ ] misc-compile-linux-mips64 (Container image)
- [ ] misc-compile-linux-mips64le (Container image)
- [ ] misc-compile-linux-mipsle (Container image)
- [ ] misc-compile-linux-ppc64 (Container image)
- [ ] misc-compile-linux-ppc64le (Container image)
- [ ] misc-compile-linux-riscv64 (Container image)
- [ ] misc-compile-linux-s390x (Container image)
- [ ] misc-compile-netbsd-386 (Container image)
- [ ] misc-compile-netbsd-amd64 (Container image)
- [ ] misc-compile-netbsd-arm (Container image)
- [ ] misc-compile-netbsd-arm64 (Container image)
- [ ] misc-compile-openbsd-386 (Container image)
- [ ] misc-compile-openbsd-arm (Container image)
- [ ] misc-compile-openbsd-arm64 (Container image)
- [ ] misc-compile-plan9-386 (Container image)
- [ ] misc-compile-plan9-amd64 (Container image)
- [ ] misc-compile-plan9-arm (Container image)
- [ ] misc-compile-solaris-amd64 (Container image)
- [ ] misc-compile-windows-arm (Container image)
- [ ] misc-compile-windows-arm64 (Container image)
- [ ] netbsd-386-9_3 (GCE VM Image)
- [ ] netbsd-amd64-9_3 (GCE VM Image)
- [ ] openbsd-386-72 (GCE VM Image)
- [ ] openbsd-amd64-72 (GCE VM Image)
- [ ] plan9-386 (GCE VM Image)
- [ ] wasip1-wasm-wasmedge (Container image)
- [ ] wasip1-wasm-wasmer (Container image)
- [ ] wasip1-wasm-wasmtime (Container image)
- [ ] wasip1-wasm-wazero (Container image)
- [ ] windows-386-2008 (GCE VM Image)
- [ ] windows-386-2008-oldcc (GCE VM Image)
- [ ] windows-386-2012 (GCE VM Image)
- [ ] windows-386-2012-oldcc (GCE VM Image)
- [ ] windows-386-2016 (GCE VM Image)
- [ ] windows-386-2016-oldcc (GCE VM Image)
- [ ] windows-amd64-2008 (GCE VM Image)
- [ ] windows-amd64-2008-oldcc (GCE VM Image)
- [ ] windows-amd64-2012 (GCE VM Image)
- [ ] windows-amd64-2012-oldcc (GCE VM Image)
- [ ] windows-amd64-2016 (GCE VM Image)
- [ ] windows-amd64-2016-oldcc (GCE VM Image)
- [ ] windows-amd64-longtest (GCE VM Image)
- [ ] windows-amd64-longtest-oldcc (GCE VM Image)
- [ ] windows-amd64-oldcc-race (GCE VM Image)
- [ ] windows-amd64-race (GCE VM Image)

@golang/release

**Comment by cagedmantis** [comment]
#60468  Is tracking the builder and images. This issue is no longer needed.
