### ISSUE TITLE
all: reopen tree for Go 1.22 development

### ISSUE THREAD

**Issue by mknyszek** [golang/go#60558]
### Current Tree Status: Tree closed for Go 1.22 general development

This is a tracking issue for the [upcoming task](https://golang.org/s/release#timeline) of reopening the tree for Go 1.22 development. (It's created a little early to create room for planning early CLs/branches to land during tree reopening.)

As usual, the tree will initially be open to changes that must land early:

- [x] Bump `internal/goversion.Version` to 22 and update the go directive in the go.mod files —this should be the very first CL to be submitted as it marks the start of `master` branch representing Go 1.22 (rather than Go 1.21). ([Example CL](https://golang.org/cl/275297).)
- [x] Any CLs associated with issues labelled as early-in-cycle.
  - [x] #60463 (cc @dmitshur)
    - (Its CLs are fine to submit after general tree opening.)
  - [x] #55160 (cc @prattmic) (can wait until after general tree opening)
- [x] Submit CLs that are already approved and marked AutoSubmit, but blocked on wait-release
- [x] Finally, open the tree for all general Go 1.22 changes.

CC @golang/release.

**Comment by mpratt** [comment]
Hi guys! 
I believe you really wanted to cc my long lost brother mr @prattmic instead of me :heart:

**Comment by heschi** [comment]
Sorry about that!

**Comment by heschi** [comment]
#61454 is fixed. Proceeding.
