### ISSUE TITLE
all: reopen tree for Go 1.22 development

### ISSUE THREAD

**Issue by heschi** [golang/go#61398]
# Current Tree Status: Tree closed for all Go 1.22 changes (see [wiki](https://github.com/golang/go/wiki/Go-Release-Cycle#january--july-week-1-planning-for-release-begins))

This is a tracking issue for the [upcoming task](https://golang.org/s/release#timeline) of reopening the tree for development. (It's created a little early to create room for planning early CLs/branches to land during tree reopening.)

As usual, the tree will initially be open to changes that must land early:

- [ ] Bump internal/goversion.Version to —this should be the very first CL to be submitted as it marks the start of master branch representing the new version. ([Example CL](https://golang.org/cl/275297).)
- [ ] Any CLs associated with issues labelled as early-in-cycle. (Detailed list being compiled)
- [ ] Finally, open the tree for all changes.

CC @golang/release.

**Comment by heschi** [comment]
Duplicate of #60558
