### ISSUE TITLE
cmd/compile: PGO devirtualization follow-ups

### ISSUE THREAD

**Issue by prattmic** [golang/go#61577]
https://go.dev/cl/492436 implements the bare minimum of a PGO devirtualization implementation. There are still numerous limitations that we would like address shortly:

- [x] Callees not directly referenced in the current package can be missed (even if they are in the transitive dependences). https://go.dev/cl/497175
- [x] Only interface method calls are supported, not other indirect function calls.
- [ ] Callees that only partially implement an interface (they are embedded in another type that completes the interface) cannot be devirtualized. -> #64673
- [ ] Closures cannot be inlined -> #64675
- [ ] Callees may be missing from export data -> #64676

cc @cherrymui @aclements

**Comment by And-ZJ** [comment]
Hello, I have a question, I found that devirtualization may not be done if the type is not exported. 
Will this approach be considered: if a hot method is found, the type that is not exported will be exported? Or some other way? Is it worth it?
Is it discussed in other issues? Sorry, I may not have noticed. Thank you!

**Comment by prattmic** [comment]
Functions/types can end up in export data even if they are not explicitly exported for a variety of reasons, which would would enable devirtualization, however they are not guaranteed to be included. We have discussed this problem a bit, but not filed an issue, so I've filed #64676.
