### ISSUE TITLE
x/website: revamp website for precise and pointed downloads, better access with content indices + user experience

### ISSUE THREAD

**Issue by odeke-em** [golang/go#63327]
We are revamping the website for https://go.dev and to that effect we have a couple of tasks whereby the finished prototype is at https://golang-doc-6yhxy5np6a-uc.a.run.app/ and to get changes in smoothly per https://github.com/orijtech/website/pull/1 and this is our game plan. **This issue is merely a progress tracker**

### Tasks
- [ ] Commit css changes: _content/css/* updates, Javascript changes _content/js
- [ ] Commit _content/doc/tutorial/`<EDITOR_GUIDES.md>`, Gopls, VimGo, VSCode and the various images
- [ ] Implement primary/left/title index
- [ ] Implement secondary/right/in-page index
- [ ] Implement the in-page progress jump buttons
- [ ] Implement new download experience
   - [ ] Content page firstly for where the downloads will be redirected to
   - [ ] UserAgent detection and redirection
   - [ ] Lastly the download button plus "Tour Go"
- [ ] Update all the menus accordingly

/cc @willpoint @jamalc @joedian
