### ISSUE TITLE
api: audit for Go 1.22

### ISSUE THREAD

**Issue by mknyszek** [golang/go#64343]
This is a tracking issue for doing an audit of API additions for Go 1.22 as of https://go.dev/cl/544555.

### archive/tar
 - [ ] pkg archive/tar, method (*Writer) AddFS(fs.FS) error #58000
 - [ ] pkg archive/tar, type FileInfoNames interface, Gname(int) (string, error) #50102
 - [ ] pkg archive/tar, type FileInfoNames interface { Gname, IsDir, ModTime, Mode, Name, Size, Sys, Uname } #50102
 - [ ] pkg archive/tar, type FileInfoNames interface, IsDir() bool #50102
 - [ ] pkg archive/tar, type FileInfoNames interface, Mode() fs.FileMode #50102
 - [ ] pkg archive/tar, type FileInfoNames interface, ModTime() time.Time #50102
 - [ ] pkg archive/tar, type FileInfoNames interface, Name() string #50102
 - [ ] pkg archive/tar, type FileInfoNames interface, Size() int64 #50102
 - [ ] pkg archive/tar, type FileInfoNames interface, Sys() interface{} #50102
 - [ ] pkg archive/tar, type FileInfoNames interface, Uname(int) (string, error) #50102
 - [ ] pkg archive/zip, method (*Writer) AddFS(fs.FS) error #54898
 
 ### cmp
 - [ ] pkg cmp, func Or[$0 comparable](...$0) $0 #60204
 
 ### crypto/x509
 - [ ] pkg crypto/x509, func OIDFromInts([]uint64) (OID, error) #60665
 - [ ] pkg crypto/x509, method (*CertPool) AddCertWithConstraint(*Certificate, func([]*Certificate) error) #57178
 - [ ] pkg crypto/x509, method (OID) EqualASN1OID(asn1.ObjectIdentifier) bool #60665
 - [ ] pkg crypto/x509, method (OID) Equal(OID) bool #60665
 - [ ] pkg crypto/x509, method (OID) String() string #60665
 - [ ] pkg crypto/x509, type Certificate struct, Policies []OID #60665
 - [ ] pkg crypto/x509, type OID struct #60665
 
 ### database/sql
 - [ ] pkg database/sql, method (*Null[$0]) Scan(interface{}) error #60370
 - [ ] pkg database/sql, method (Null[$0]) Value() (driver.Value, error) #60370
 - [ ] pkg database/sql, type Null[$0 interface{}] struct #60370
 - [ ] pkg database/sql, type Null[$0 interface{}] struct, V $0 #60370
 - [ ] pkg database/sql, type Null[$0 interface{}] struct, Valid bool #60370
 
 ### debug/elf
 - [ ] pkg debug/elf, const R_LARCH_64_PCREL = 109 #63725
 - [ ] pkg debug/elf, const R_LARCH_64_PCREL R_LARCH #63725
 - [ ] pkg debug/elf, const R_LARCH_ADD6 = 105 #63725
 - [ ] pkg debug/elf, const R_LARCH_ADD6 R_LARCH #63725
 - [ ] pkg debug/elf, const R_LARCH_ADD_ULEB128 = 107 #63725
 - [ ] pkg debug/elf, const R_LARCH_ADD_ULEB128 R_LARCH #63725
 - [ ] pkg debug/elf, const R_LARCH_ALIGN = 102 #63725
 - [ ] pkg debug/elf, const R_LARCH_ALIGN R_LARCH #63725
 - [ ] pkg debug/elf, const R_LARCH_CFA = 104 #63725
 - [ ] pkg debug/elf, const R_LARCH_CFA R_LARCH #63725
 - [ ] pkg debug/elf, const R_LARCH_DELETE = 101 #63725
 - [ ] pkg debug/elf, const R_LARCH_DELETE R_LARCH #63725
 - [ ] pkg debug/elf, const R_LARCH_PCREL20_S2 = 103 #63725
 - [ ] pkg debug/elf, const R_LARCH_PCREL20_S2 R_LARCH #63725
 - [ ] pkg debug/elf, const R_LARCH_SUB6 = 106 #63725
 - [ ] pkg debug/elf, const R_LARCH_SUB6 R_LARCH #63725
 - [ ] pkg debug/elf, const R_LARCH_SUB_ULEB128 = 108 #63725
 - [ ] pkg debug/elf, const R_LARCH_SUB_ULEB128 R_LARCH #63725
 - [ ] pkg debug/elf, const R_MIPS_PC32 = 248 #61974
 - [ ] pkg debug/elf, const R_MIPS_PC32 R_MIPS #61974
 
 ### encoding/base32
 - [ ] pkg encoding/base32, method (*Encoding) AppendDecode([]uint8, []uint8) ([]uint8, error) #53693
 - [ ] pkg encoding/base32, method (*Encoding) AppendEncode([]uint8, []uint8) []uint8 #53693
 
 ### encoding/base64
 - [ ] pkg encoding/base64, method (*Encoding) AppendDecode([]uint8, []uint8) ([]uint8, error) #53693
 - [ ] pkg encoding/base64, method (*Encoding) AppendEncode([]uint8, []uint8) []uint8 #53693
 
 ### encoding/hex
 - [ ] pkg encoding/hex, func AppendDecode([]uint8, []uint8) ([]uint8, error) #53693
 - [ ] pkg encoding/hex, func AppendEncode([]uint8, []uint8) []uint8 #53693
 
 ### go/ast
 - [ ] pkg go/ast, func Unparen(Expr) Expr #60061
 
 ### go/types
 - [ ] pkg go/types, func NewAlias(*TypeName, Type) *Alias #63223
 - [ ] pkg go/types, func Unalias(Type) Type #63223
 - [ ] pkg go/types, method (*Alias) Obj() *TypeName #63223
 - [ ] pkg go/types, method (*Alias) String() string #63223
 - [ ] pkg go/types, method (*Alias) Underlying() Type #63223
 - [ ] pkg go/types, method (Checker) PkgNameOf(*ast.ImportSpec) *PkgName #62037
 - [ ] pkg go/types, method (*Info) PkgNameOf(*ast.ImportSpec) *PkgName #62037
 - [ ] pkg go/types, type Alias struct #63223
 - [ ] pkg go/types, type Info struct, FileVersions map[*ast.File]string #62605
 
 ### go/version
 - [ ] pkg go/version, func Compare(string, string) int #62039
 - [ ] pkg go/version, func IsValid(string) bool #62039
 - [ ] pkg go/version, func Lang(string) string #62039
 
 ### html/template
 - [ ] pkg html/template, const ErrJSTemplate //deprecated #61619
 
 ### io
 - [ ] pkg io, method (*SectionReader) Outer() (ReaderAt, int64, int64) #61870
 
 ### log/slog
 - [ ] pkg log/slog, func SetLogLoggerLevel(Level) Level #62418
 
 ### math/big
 - [ ] pkg math/big, method (*Rat) FloatPrec() (int, bool) #50489
 
 ### math/rand/v2
 - [ ] pkg math/rand/v2, func ExpFloat64() float64 #61716
 - [ ] pkg math/rand/v2, func Float32() float32 #61716
 - [ ] pkg math/rand/v2, func Float64() float64 #61716
 - [ ] pkg math/rand/v2, func Int32() int32 #61716
 - [ ] pkg math/rand/v2, func Int32N(int32) int32 #61716
 - [ ] pkg math/rand/v2, func Int64() int64 #61716
 - [ ] pkg math/rand/v2, func Int64N(int64) int64 #61716
 - [ ] pkg math/rand/v2, func Int() int #61716
 - [ ] pkg math/rand/v2, func IntN(int) int #61716
 - [ ] pkg math/rand/v2, func N[$0 intType]($0) $0 #61716
 - [ ] pkg math/rand/v2, func NewPCG(uint64, uint64) *PCG #61716
 - [ ] pkg math/rand/v2, func New(Source) *Rand #61716
 - [ ] pkg math/rand/v2, func NewZipf(*Rand, float64, float64, uint64) *Zipf #61716
 - [ ] pkg math/rand/v2, func NormFloat64() float64 #61716
 - [ ] pkg math/rand/v2, func Perm(int) []int #61716
 - [ ] pkg math/rand/v2, func Shuffle(int, func(int, int)) #61716
 - [ ] pkg math/rand/v2, func Uint32N(uint32) uint32 #61716
 - [ ] pkg math/rand/v2, func Uint32() uint32 #61716
 - [ ] pkg math/rand/v2, func Uint64N(uint64) uint64 #61716
 - [ ] pkg math/rand/v2, func Uint64() uint64 #61716
 - [ ] pkg math/rand/v2, func UintN(uint) uint #61716
 - [ ] pkg math/rand/v2, method (*PCG) MarshalBinary() ([]uint8, error) #61716
 - [ ] pkg math/rand/v2, method (*PCG) Seed(uint64, uint64) #61716
 - [ ] pkg math/rand/v2, method (*PCG) Uint64() uint64 #61716
 - [ ] pkg math/rand/v2, method (*PCG) UnmarshalBinary([]uint8) error #61716
 - [ ] pkg math/rand/v2, method (*Rand) ExpFloat64() float64 #61716
 - [ ] pkg math/rand/v2, method (*Rand) Float32() float32 #61716
 - [ ] pkg math/rand/v2, method (*Rand) Float64() float64 #61716
 - [ ] pkg math/rand/v2, method (*Rand) Int32() int32 #61716
 - [ ] pkg math/rand/v2, method (*Rand) Int32N(int32) int32 #61716
 - [ ] pkg math/rand/v2, method (*Rand) Int64() int64 #61716
 - [ ] pkg math/rand/v2, method (*Rand) Int64N(int64) int64 #61716
 - [ ] pkg math/rand/v2, method (*Rand) Int() int #61716
 - [ ] pkg math/rand/v2, method (*Rand) IntN(int) int #61716
 - [ ] pkg math/rand/v2, method (*Rand) NormFloat64() float64 #61716
 - [ ] pkg math/rand/v2, method (*Rand) Perm(int) []int #61716
 - [ ] pkg math/rand/v2, method (*Rand) Shuffle(int, func(int, int)) #61716
 - [ ] pkg math/rand/v2, method (*Rand) Uint32N(uint32) uint32 #61716
 - [ ] pkg math/rand/v2, method (*Rand) Uint32() uint32 #61716
 - [ ] pkg math/rand/v2, method (*Rand) Uint64N(uint64) uint64 #61716
 - [ ] pkg math/rand/v2, method (*Rand) Uint64() uint64 #61716
 - [ ] pkg math/rand/v2, method (*Rand) UintN(uint) uint #61716
 - [ ] pkg math/rand/v2, method (*Zipf) Uint64() uint64 #61716
 - [ ] pkg math/rand/v2, type PCG struct #61716
 - [ ] pkg math/rand/v2, type Rand struct #61716
 - [ ] pkg math/rand/v2, type Source interface { Uint64 } #61716
 - [ ] pkg math/rand/v2, type Source interface, Uint64() uint64 #61716
 - [ ] pkg math/rand/v2, type Zipf struct #61716
 
 ### net/http
 - [ ] pkg net/http, func FileServerFS(fs.FS) Handler #51971
 - [ ] pkg net/http, func NewFileTransportFS(fs.FS) RoundTripper #51971
 - [ ] pkg net/http, func ServeFileFS(ResponseWriter, *Request, fs.FS, string) #51971
 - [ ] pkg net/http, method (*Request) PathValue(string) string #61410
 - [ ] pkg net/http, method (*Request) SetPathValue(string, string) #61410
 
 ### net
 - [ ] pkg net, method (*TCPConn) WriteTo(io.Writer) (int64, error) #58808
 
 ### net/netip
 - [ ] pkg net/netip, method (AddrPort) Compare(AddrPort) int #61642
 - [ ] pkg net/netip, method (Prefix) Compare(Prefix) int #61642
 
 ### os
 - [ ] pkg os, method (*File) WriteTo(io.Writer) (int64, error) #58808
 
 ### reflect
 - [ ] pkg reflect, func PtrTo //deprecated #59599
 - [ ] pkg reflect, func TypeFor[$0 interface{}]() Type #60088
 
 ### slices
 - [ ] pkg slices, func Concat[$0 interface{ ~[]$1 }, $1 interface{}](...$0) $0 #56353
 
 ### syscall
 - [ ] pkg syscall (linux-386-cgo), type SysProcAttr struct, PidFD *int #51246
 - [ ] pkg syscall (linux-386), type SysProcAttr struct, PidFD *int #51246
 - [ ] pkg syscall (linux-amd64-cgo), type SysProcAttr struct, PidFD *int #51246
 - [ ] pkg syscall (linux-amd64), type SysProcAttr struct, PidFD *int #51246
 - [ ] pkg syscall (linux-arm-cgo), type SysProcAttr struct, PidFD *int #51246
 - [ ] pkg syscall (linux-arm), type SysProcAttr struct, PidFD *int #51246
 
 ### testing/slogtest
 - [ ] pkg testing/slogtest, func Run(*testing.T, func(*testing.T) slog.Handler, func(*testing.T) map[string]interface{}) #61758

**Comment by mateusz834** [comment]
Related #64012

**Comment by rsc** [comment]
Went through them all. LGTM. This is much easier now that we have issues linked in the api files.

The program that posts the audit issue needs to be updated to escape [ in api lines when creating the markdown. See cmp.Compare above for why.
