### ISSUE TITLE
x/telemetry, cmd/go: umbrella issue for cmd/go integration

### ISSUE THREAD

**Issue by findleyr** [golang/go#65586]
This is an umbrella issue tracking work to integrate opt-in telemetry with cmd/go for Go 1.23. This augments #58894 with specific items necessary for cmd/go.

Here are some high level steps:

- [x] Vendor x/telemetry and call counter.Open (done in https://go.dev/cl/559199)
- [x] Add at least one counter (e.g. flag usage). (https://go.dev/cl/559519, reverted due to windows/386 test failure in #65447)
- [x] File at least one [public telemetry proposal](https://github.com/golang/go/issues/new?assignees=&labels=Telemetry-Proposal&projects=golang%2F29&template=12-telemetry.yml&title=x%2Ftelemetry%2Fconfig%3A+proposal+title) for collection of a Go command counter.
- [x] Observe counters being reported to telemetry.go.dev. This will happen even before the next step, from users that run gopls.
- [x] Design a mechanism for lighter-weight uploading (e.g. #65500, though that need not be the solution). Necessary features:
  - [x] Rate limit uploading. E.g. only one process per day calls `upload.Run`.
  - [x] Daemonize uploading. Uploads should be detached from short-lived Go command invocations.
  - [x] Decide when uploading should be attempted. For example, we could only attempt during `go build`, or use a heuristic such as a 1s delay from process start.

CC @golang/telemetry

**Comment by cagedmantis** [comment]
Is there any status update to report on this issue?

**Comment by matloob** [comment]
We've gotten counters into the go command and are working on integrating them into other commands. We have a telemetry counter config proposal out (https://github.com/golang/go/issues/66210).

**Comment by cherrymui** [comment]
@matloob this is a release blocker. Any update on the counters? Thanks.

**Comment by matloob** [comment]
Hi we plan to have counters flowing onto the website and a collection proposal out by the end of the week.
I have a CL out to add counters to the compiler and will soon send out CLs for the other tools.

**Comment by cagedmantis** [comment]
@matloob Is there is status update on this issue? This came up in the release meeting.

**Comment by findleyr** [comment]
I checked the last box, since we have observed counters.

@matloob I think this can be closed.

**Comment by matloob** [comment]
Closing.
