### ISSUE TITLE
all: reopen tree for Go 1.25 development

### ISSUE THREAD

**Issue by dmitshur** [golang/go#70525]
### Current Tree Status: Tree is open for Go 1.25 development ([golang-dev announcement](https://groups.google.com/g/golang-dev/c/OmqSdlin4Nc/m/5ExCl3Y4CwAJ))

Now that we've entered the freeze for Go 1.24, we will eventually need to reopen the tree for Go 1.25 development. This is the tracking issue for that reopening, created early so that it's available for planning. The tree reopening is estimated to begin around week 3 of January 2025 (see https://go.dev/s/release#timeline), exact timing depends on how well the Go 1.24 release preparations are going.

As usual, the tree will initially be open to changes that must land early:

- [x] Bump `internal/goversion.Version` to 25—this should be the very first CL to be submitted as it marks the start of main branch representing Go 1.25 (rather than Go 1.24). ([Example CL](https://go.dev/cl/600176).)
  - #40705
- [x] Initialize `doc/next` for the Go 1.25 cycle. (See "For the release team" in [doc/README](https://cs.opensource.google/go/go/+/master:doc/README.md).)
- [x] Submit CLs that are ready and marked AutoSubmit+1, but blocked on wait-release ([query](https://go-review.googlesource.com/q/is:open+label:Auto-Submit%3D%252B1+label:Code-Review%3D%252B2+-label:Hold%3D%252B1+-label:TryBots-Pass%3DNEED+-label:Legacy-TryBots-Pass%3DNEED+-has:unresolved+hashtag:wait-release+-is:wip+-label:Do-Not-Review%3DNEED+-label:Do-Not-Submit%3DNEED)).
- [x] Look over issues labelled as [early-in-cycle](https://github.com/golang/go/issues?q=is%3Aopen+is%3Aissue+label%3Aearly-in-cycle+milestone%3AGo1.25) for anything needs to land very early.
- [x] Submit CL for #49580.
- _(Anything else that is missing but should be added here, edit or comment below.)_
- [x] A brief soft-reopening window, where any fix/stabilization CLs are okay to submit.
- [x] Finally, open the tree for all general Go 1.25 changes.

CC @golang/release.

**Comment by cherrymui** [comment]
Done.

**Comment by mateusz834** [comment]
FYI, go.mod still say go 1.24

https://github.com/golang/go/blob/ee6e0a5ed6a11f79f40ca58ca5337ec5bad16ebb/src/go.mod#L3

Not sure whether this needs to be changed too, looking at blame it was changed with deps update before ([CL 600535](https://go.dev/cl/600535)). I noticed this because i had not updated my `$PATH`, thus:

```go
[mateusz@arch src (master)]$ go version
go: downloading go1.24.0 (linux/amd64)
```

**Comment by cherrymui** [comment]
Thanks for bringing this up. Updating the vendored dependencies is #36905, which I plan to do later this week.
