### ISSUE TITLE
x/tools/gopls/internal/analysis: add "modernizer" analyzers

### ISSUE THREAD

**Issue by adonovan** [golang/go#70815]
[Note: please create new issues for bugs and feature requests rather than expanding the scope of this one.]

Between generics, iterators, min and max, new standard packages such as `slices`, `maps`, and `cmp`, there are a large number of new ways to write Go code more concisely and no less clearly. We should develop "modernizer" analyzer(s) that identify such opportunities and offer suggested fixes.

Many of these are already implemented in `staticcheck` (see [S1000](https://staticcheck.dev/docs/checks/) et seq); we would just need to enable them.

When the appropriate fix is to inline a call to a deprecated function whose body illustrates the recommended approach (e.g. a call to a more modern function, as in the case of the functions in the golang.org/x/exp/maps package), these will be handled by annotating the deprecated function as prescribed by proposal #32816, and letting the [inliner](https://go.dev/cl/634919) take care of it.

Examples:

- [x] b.N → b.Loop in Benchmarks (https://go.dev/cl/638337)
-  [x] interface{} → any (CL 636276)
 - [x] explicit loops → slices.{Equal,Compare,Index,Contains}{,Func}. The challenge is treating the `return false` and `return true` steps in the slices package as wildcards that match "equal and opposite" actions--not just return statements--in the user code. (CL 640576)
 - [x] explicit loops → maps.{Clone,Collect.Insert,Copy} (https://go.dev/cl/638875)
 - ~maps.Keys(m) + slices.Collect (or loop equivalent of Keys+Collect) + sort -> `slices.Sorted(maps.Keys(m))`. Eliminate temporaries when used once in `range _`. Downside: de-optimizes preallocation of correct array size; perhaps best left until resolution of #68598.~
 - [x] various append + s[::] combinations -> slices.Grow, Clip, Concat & Clone (https://go.dev/cl/637735), etc.
 - [x] `append(s[:i], s[i+k:]...)` -> `slices.Delete(s, i, i+k)`, where k is a non-negative constant
 - [x] exp/{slices,maps} -> std {slices,maps} (see CL 635680 + issue #32816)
 - [x] [exp/maps.Clear](https://github.com/golang/go/issues/70717) → clear etc (https://go.dev/cl/635680)
 - [x] if/else → min/max ([CL 635777](https://go.dev/cl/635777))
 - ~awkward logic in slice.Sort's less function → `if cmp := cmp.Compare(x, y); cmp != 0 { return cmp < 0 }`~
 - [x] sort.Slice -> slices.Sort, avoiding the less func when it is the natural order (https://go.dev/cl/635681)
 - ~sort.Slice -> slices.SortFunc, eliminating the indices~
-  [x] json:omitempty → json:omitzero for basic types
 - ~SetFinalizer → AddCleanup~
 - ~use strings.Lines instead of strings.Split("\n") (but: "\r"?!) or text.scanner(strings.NewReader)/Scan/Text~
 - [x] `[]byte(fmt.Sprintf...)` → `fmt.Appendf(nil, ...)` (https://go.dev/cl/638436)
 - ~implementing {Text,Binary}Appender for types that currently implement {Text,Binary}Marshaler~
 - [x] replacing `ctx, cancel := context.WithCancel(context.Background()); defer cancel()` in tests with `ctx := t.Context()`.
- [ ] use cipher.NewGCMWithRandomNonce where possible ([example](https://go.dev/play/p/BrT5grsl3cO?v=gotip))
- [x] reflect.DeepEqual(x, y []comparable) -> slices.Equal(x, y) (CL 649457)
- [x] for range strings.Split -> for range strings.SplitSeq (CL 647438)
- [ ] ditto for strings.Fields{,Seq} (split out to separate issue #72033)
- [x] `for i := 0; i < n; i++ {}` => `for i := range n {}` (CL 646916)

They should of course all respect the effective version of Go determined by go.mod and build tags.

@aclements

**Comment by zephyrtronium** [comment]
Would it make sense for some of these to be depreciations instead? Particularly looking at x/exp/maps.Clear and the go/* upgrades.

**Comment by adonovan** [comment]
> Would it make sense for some of these to be depreciations instead? Particularly looking at x/exp/maps.Clear and the go/* upgrades.

Even if we were to deprecate maps.Clear (which is perfectly fine function), users would still want a way to migrate their code away from it. So I see deprecation as independent. And in many cases the pattern being "modernized" is not just a simple use of one symbol that could be deprecated.

**Comment by aclements** [comment]
Some of these (maybe all :smile: ) are subtler than they appear on the tin.

> b.N → b.Loop in Benchmarks

The core of this is just replacing `for range b.N` with `for b.Loop()`, but a major point of `b.Loop()` is that it allows other simplifications, like you don't have to reset the timer after setup, or go out of your way to cache complex setup steps, or stop the timer after the loop for expensive cleanup steps.

> SetFinalizer → AddCleanup

Here you have to identify the underlying "resource" that's being freed by the finalizer since that's what `AddCleanup` attaches.

> use strings.Lines

There are so many patterns for splitting a string into lines right now. I'm really curious how we'd pick up on that.

> implementing {Text,Binary}Appender for types that currently implement {Text,Binary}Marshaler

In addition to creating Append methods, ideally this should also rewrite `MarshalText`/`MarshalBinary` to use the new Append methods.

**Comment by findleyr** [comment]
This is great. Let's try to get as many of these done for gopls@v0.18.0, to enhance the theme of the release.

Assigning @adonovan and @madelinekalil, who are working on it.

**Comment by adonovan** [comment]
I notice Stroustrup has long used term "rejuvenation" for this kind of program transformation.

"Source Code Rejuvenation Is Not Refactoring", Pirkelbauer, Dechev & Stroustrup (2010)
https://link.springer.com/chapter/10.1007/978-3-642-11266-9_53

"Rejuvenating C++ Programs through Demacrofication", Kumar, Sutton & Stroustrup (2012)
https://www.stroustrup.com/icsm-2012-demacro.pdf

"Continuous Source Code Rejuvenation in Continuous Integration Pipelines", Fülöp, Pataki & Szauter (2022)
https://ceur-ws.org/Vol-3845/paper08.pdf

**Comment by aclements** [comment]
Another possible modernizer was mentioned [here](https://github.com/golang/go/issues/36532#issuecomment-2568962116): Replace `ctx, cancel := context.WithCancel(context.Background()); defer cancel()` in tests with `t.Context()`

**Comment by findleyr** [comment]
> Another possible modernizer was mentioned [here](https://github.com/golang/go/issues/36532#issuecomment-2568962116): Replace `ctx, cancel := context.WithCancel(context.Background()); defer cancel()` in tests with `ctx := t.Context()`

Thanks, that looks relatively straightforward. I'll pick it up.

**Comment by stapelberg** [comment]
@findleyr asked me to leave a note here regarding a false-positive modernizer issue I found. With gopls from x/tools at revision 1b796a93b9c5e1f507618de1d18d5908df5e3702, when I put the following code into VS Code:

```go
package main

import "fmt"

func main() {
	cur := make(map[int32]int)
	countsB := map[int32]int{1: 23, 2: 42}
	for k, v := range countsB {
		cur[k] += v
	}
	countsA := map[int32]int{1: 23, 2: 42}
	for k, v := range countsA {
		cur[k] += v
	}
	// prints: map[1:46 2:84]
	fmt.Printf("cur: %+v\n", cur)
}
```

I get a blue squiggly under both “cur[k]”: 

<img width="561" alt="Screenshot 2025-01-10 at 08 58 26" src="https://github.com/user-attachments/assets/34a310ad-6d28-40d5-a3ec-0cd917b56c88" />


Applying the quick fix changes the code to this:

```go
package main

import "maps"

import "fmt"

func main() {
	cur := make(map[int32]int)
	countsB := map[int32]int{1: 23, 2: 42}
	maps.Copy(cur, countsB)
	countsA := map[int32]int{1: 23, 2: 42}
	maps.Copy(cur, countsA)
	// prints: map[1:46 2:84]
	fmt.Printf("cur: %+v\n", cur)
}
```

…but the docs of maps.Copy say:

> Copy copies all key/value pairs in src adding them to dst. When a key in src is already present in dst, the value in dst will be overwritten by the value associated with the key in src.

…and indeed, the code no longer produces the same result: It now incorrectly prints “map[1:23 2:42]”

**Comment by adonovan** [comment]
Thanks for the exemplary bug report. I forgot to check the operator used by the AssignStmt--too easily done.

**Comment by dsnet** [comment]
Would #69820 be a good candidate for a modenizer?

**Comment by adonovan** [comment]
> Would [#69820](https://github.com/golang/go/issues/69820) be a good candidate for a modenizer?

It's certainly an easy thing to implement. I'm not sure how frequent it is. The [summary](https://github.com/golang/go/issues/69820#issuecomment-2408651949) is:

```go
var slice []T
const k
*(*[k]T)(slice)  =>  [k]T(slice)  // when used as rvalue
```

**Comment by findleyr** [comment]
@adonovan I encountered a bug in the slices.Contains modernizer today.

Modernizing using slices.Contains here results in an error:
https://cs.opensource.google/go/x/tools/+/master:gopls/internal/golang/highlight.go;l=348;drc=344e48255740736de8c8277e9a286cf3231c7e13

```go
		case *ast.CallExpr:
			// If cursor is an arg in a callExpr, we don't want control flow highlighting.
			if i > 0 {
				for _, arg := range n.Args {
					if arg == path[i-1] {
						return
					}
				}
			}
```

Error is: `S (type []ast.Expr) does not satisfy ~[]E`.
For now, I think we need to check that the types in the match condition are identical.

**Comment by adonovan** [comment]
Thanks; I split this out into its own issue: https://github.com/golang/go/issues/71313

**Comment by findleyr** [comment]
> Thanks; I split this out into its own issue: https://github.com/golang/go/issues/71313

Made that a sub-issue of this one. Neat! We're living in the future.

**Comment by josharian** [comment]
A modernization I often do by hand is using {strings,bytes}.Cut{,Prefix,Suffix}.

**Comment by dsnet** [comment]
> It doesn't turn up a single instance in the entire k8s codebase (~3MLoC), so the juice is not worth the squeeze.

😅  Thank you for testing that out.

**Comment by apocelipes** [comment]
Would `cmp.Compare(str1, str2) -> strings.Compare(str1, str2)` be a good candidate for a modenizer? The `strings.Compare` is more efficient and seems to have clearer semantics.

**Comment by earthboundkid** [comment]
When I tried to run this, I got an error. Is this expected?

```
$ go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@1320197d6c7ed6da48496e5e311c7ee76701e035
 -fix
go: golang.org/x/tools/gopls@v0.0.0-20250206210647-1320197d6c7e requires go >= 1.23.4; switching to go1.23.6
go: golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@1320197d6c7ed6da48496e5e311c7ee76701e035 (in golang.org/x/tools/gopls@v0.0.0-20250206210647-1320197d6c7e):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by adonovan** [comment]
> [@adonovan](https://github.com/adonovan) When you are done, could you please also turn this into a more regular pass so we can monitor and fix regressions in that area using a golanci-lint integration of that linter?

Do you mean: can we publish the modernize analyzer as a subpackage of go/analysis/passes, so that golangci-lint can include it in its set? That's certainly something we could do, though of course every new API symbol requires a proposal; but we are at the beginning of a series of discussions about how to generalize modernizers (and by implication analyzers in general) so that they can be defined by third-party projects too. We should probably wait till that picture emerges clearly before committing to publish the modernize analyzer.

**Comment by adonovan** [comment]
> One thought: when suggesting to replace `append([]byte{}, p...)` with `slices.Clone`, if the file or package in question already uses the `bytes` package elsewhere but not the `slices` package, I think that implies that `bytes.Clone` would be a mildly better replacement. Because in one example I just ran into, the package in question was relatively low level, so mixing the bytes and slices packages seemed unnecessary.
> 
> In general I think the same applies to any suggestions to use the `slices` package for operations on `[]byte` where the file already uses the bytes package but not the slices package. IMHO local consistency is relatively important.

This is now done.

**Comment by adonovan** [comment]
I have split all remaining tasks out into separate issues, linked from the issue body above, with the exception of

- use cipher.NewGCMWithRandomNonce where possible ([example](https://go.dev/play/p/BrT5grsl3cO?v=gotip))

which I suspect is too infrequent to be worth the trouble. Please create new issues for bugs of feature requests; this issue is done.
